# Generated by Django 4.1 on 2025-12-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_actors_movie_genres"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={},
        ),
    ]
